import {useEffect,useState} from 'react';
import {depositCoverage,depositDayLabel} from './deposit-coverage.js';
import {DepositCoverageLines} from './deposit-coverage.jsx';
const php=n=>new Intl.NumberFormat('en-PH',{style:'currency',currency:'PHP'}).format(Number(n||0));
export function AdminDepositCards({branch,role,api,HistoryCard}) {
  const [data,setData]=useState(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false);
  const [station,setStation]=useState('');const [status,setStatus]=useState('');const [selected,setSelected]=useState('');
  async function reload(){setData(await api('deposits',{branch}));}
  useEffect(()=>{let active=true;api('deposits',{branch}).then(d=>active&&setData(d)).catch(e=>active&&setError(e.message));return()=>{active=false;};},[api,branch]);
  async function settings(day){setBusy(true);setError('');const days=data.noDepositDays.includes(day)?data.noDepositDays.filter(d=>d!==day):[...data.noDepositDays,day];try{await api('settings',{noDepositDays:days});await reload();}catch(e){setError(e.message);}finally{setBusy(false);}}
  const deposits=(data?.deposits||[]).filter(d=>(!station||d.branch===station)&&(!status||d.status===status));const detail=data?.deposits.find(d=>d.id===selected);
  return <section className="section"><h2>Deposit Settings</h2>{error&&<p className="error" role="alert">{error}</p>}{!data&&!error&&<p>Loading deposits…</p>}{detail?<><button className="secondary" type="button" onClick={()=>setSelected('')}>← Back to deposit cards</button><HistoryCard deposit={detail} deposits={data.deposits} role={role} onReviewed={reload}/></>:<><p>Cards show the cashier reports covered. Select a card to see its details.</p><div className="grid two"><label>Station<select value={station} onChange={e=>setStation(e.target.value)}><option value="">All stations</option>{[...new Set((data?.deposits||[]).map(d=>d.branch))].map(b=><option key={b}>{b}</option>)}</select></label><label>Deposit status<select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All deposits</option><option value="pending">For verification</option><option value="verified">Verified</option><option value="rejected">Rejected</option></select></label></div><div className="deposit-card-grid form-space">{[...deposits].reverse().map(d=><button type="button" className="deposit-shift-card saved" key={d.id} onClick={()=>setSelected(d.id)}><span className="deposit-card-top"><strong>{d.branch}</strong><span className={'deposit-card-status '+d.status}>{d.status==='pending'?'For verification':d.status==='verified'?'Verified':'Rejected'}</span></span><strong>{depositCoverage(d,data.deposits).title}</strong><DepositCoverageLines deposit={d} deposits={data.deposits}/><strong className="deposit-card-amount">{php(d.amount)}</strong><span>{d.bank} · {d.reference}{d.partial?' · Partial':''}</span><small>Bank deposit date: {depositDayLabel(d.depositDate)}</small><span className="deposit-card-bottom">View deposit →</span></button>)}</div>{data&&!deposits.length&&<p className="deposit-empty">No deposits match these filters.</p>}{role==='Admin'&&data&&<details className="deposit-optional"><summary>Change no-deposit days</summary><p>Current: {data.noDepositDays.length?data.noDepositDays.map(i=>['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'][i]).join(', '):'Deposits allowed every day'}. Cash due on these days moves to the next deposit day.</p><div className="demo-actions">{['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'].map((day,i)=><label key={day}><input type="checkbox" disabled={busy} checked={data.noDepositDays.includes(i)} onChange={()=>settings(i)}/>{day}</label>)}</div></details>}</>}</section>;
}
