import { CASH_DENOMINATIONS, denominationTotal } from './error-reduction.ts';
const php=n=>new Intl.NumberFormat('en-PH',{style:'currency',currency:'PHP'}).format(n);
export function CashDenominations({counts={},onChange,disabled=false,label='Cash count'}) {
  let total=null,error='';try{total=denominationTotal(counts);}catch(e){if(Object.values(counts).some(v=>v!==''&&v!=null))error=e.message;}
  return <fieldset className="cash-denominations" disabled={disabled}><legend>{label}</legend><p>Enter how many notes or coins you have. Blank rows count as zero.</p><div className="denomination-table"><div className="denomination-row denomination-head"><span>Denomination</span><span>Quantity</span><span>Amount</span></div>{CASH_DENOMINATIONS.map(value=><div className="denomination-row" key={value}><strong>{php(value)}</strong><input aria-label={`${label} ₱${value} quantity`} type="text" inputMode="numeric" pattern="[0-9]*" placeholder="0" value={counts[value]??''} onChange={e=>onChange({...counts,[value]:e.target.value})}/><span>{/^(0|[1-9]\d*)$/.test(String(counts[value]||0))?php(value*Number(counts[value]||0)):'—'}</span></div>)}</div><div className="denomination-total"><span>Total physical cash</span><strong>{total===null?'—':php(total)}</strong></div>{error&&<p className="error" role="alert">{error}</p>}</fieldset>;
}

export function AutomaticVouchers({report}) {
  return <section className="section"><h2>Cash Vouchers · Automatic</h2><p>Imported from FuelTech CV · <strong>Demo sample connection</strong></p><p>Approved station vouchers mean cash released and are deducted from their assigned shift. Change the voucher in the CV app, not here.</p>{report.purchaseRows?.length?<div className="coverage-list">{report.purchaseRows.map(row=><div key={row.id}><span><b>{row.category}</b> · {row.item}<small className="cv-source">{row.source==='FuelTech CV'?`${row.sourceVoucherId} · Imported`:'Previously recorded entry · Preserved'}</small></span><strong>{php(Number(row.amount))}</strong></div>)}</div>:<p>No cash vouchers for this shift.</p>}<p><b>Total CV deductions: {php((report.purchaseRows||[]).reduce((sum,row)=>sum+Number(row.amount||0),0))}</b></p></section>;
}
