import React, { lazy, Suspense, useEffect, useState } from 'react';
const Pilot=lazy(()=>import('./PilotApp.jsx'));
export default function PilotGate() {
  const [config,setConfig]=useState(null),[error,setError]=useState('');
  useEffect(()=>{let active=true;const check=()=>fetch('/api/pilot/config',{cache:'no-store'}).then(async r=>{const value=await r.json();if(!r.ok)throw Error(value.error);if(active){window.__fueltechPilotConfig=value;setConfig(value);setError('');}}).catch(e=>{if(active)setError(e.message);});check();const timer=setInterval(check,15000);return()=>{active=false;clearInterval(timer);};},[]);
  if(error||config?.mode==='disabled') return <main className="section"><h1>Liloan pilot</h1><p>{error||'The pilot has not been enabled yet. Existing station reports remain available in the regular app.'}</p><a href="/">Open existing app</a></main>;
  if(!config) return <p>Checking pilot configuration…</p>;
  if(config.mode==='live'&&config.launch&&!config.launch.ready) return <main className="section" style={{maxWidth:680,margin:'40px auto',padding:24}}><h1>Liloan fresh start</h1><p>The new system starts <strong>{config.start_date} at 4:00 a.m.</strong> Manila time.</p><h2>Opening setup</h2><p>Finish and submit <strong>{config.launch.openingDate} Shift 3</strong> in the existing app. Its final pump readings and tank inventory become the new opening balances.</p><p>{config.launch.openingReady?'Shift 3 opening readings are ready.':'Waiting for complete, submitted Shift 3 readings.'} {!config.launch.timeReached?'New shift reporting will unlock at the start time.':''}</p><p>This screen checks automatically every 15 seconds.</p><p><a href="/cashier">Complete Shift 3 in the existing app</a></p><p><a href="/liloan-guide.html">Read the simple station guide</a></p></main>;
  return <>{config.mode==='shadow'&&<aside className="demo-banner"><div><strong>FUELTECH · LILOAN TRIAL</strong><span>Trial records are separate from official reports. · From {config.start_date}</span></div><nav>{['cashier','manager','approver','admin'].map(role=><a key={role} href={'/pilot/'+role}>{role==='approver'?'Bank Verifier':role}</a>)}</nav></aside>}<Suspense fallback={<p>Loading station…</p>}><Pilot/></Suspense></>;
}
